// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.7
// source: intgtest/internal/rpcs/rpcs.proto

package rpcs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EchoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Body    string `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	DelayMs int64  `protobuf:"varint,2,opt,name=delayMs,proto3" json:"delayMs,omitempty"`
}

func (x *EchoRequest) Reset() {
	*x = EchoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_intgtest_internal_rpcs_rpcs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EchoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoRequest) ProtoMessage() {}

func (x *EchoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_intgtest_internal_rpcs_rpcs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoRequest.ProtoReflect.Descriptor instead.
func (*EchoRequest) Descriptor() ([]byte, []int) {
	return file_intgtest_internal_rpcs_rpcs_proto_rawDescGZIP(), []int{0}
}

func (x *EchoRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *EchoRequest) GetDelayMs() int64 {
	if x != nil {
		return x.DelayMs
	}
	return 0
}

type EchoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Body string `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *EchoResponse) Reset() {
	*x = EchoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_intgtest_internal_rpcs_rpcs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EchoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoResponse) ProtoMessage() {}

func (x *EchoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_intgtest_internal_rpcs_rpcs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoResponse.ProtoReflect.Descriptor instead.
func (*EchoResponse) Descriptor() ([]byte, []int) {
	return file_intgtest_internal_rpcs_rpcs_proto_rawDescGZIP(), []int{1}
}

func (x *EchoResponse) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

var File_intgtest_internal_rpcs_rpcs_proto protoreflect.FileDescriptor

var file_intgtest_internal_rpcs_rpcs_proto_rawDesc = []byte{
	0x0a, 0x21, 0x69, 0x6e, 0x74, 0x67, 0x74, 0x65, 0x73, 0x74, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x6c, 0x2f, 0x72, 0x70, 0x63, 0x73, 0x2f, 0x72, 0x70, 0x63, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x04, 0x72, 0x70, 0x63, 0x73, 0x22, 0x3b, 0x0a, 0x0b, 0x45, 0x63, 0x68,
	0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x18, 0x0a, 0x07,
	0x64, 0x65, 0x6c, 0x61, 0x79, 0x4d, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x64,
	0x65, 0x6c, 0x61, 0x79, 0x4d, 0x73, 0x22, 0x22, 0x0a, 0x0c, 0x45, 0x63, 0x68, 0x6f, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x32, 0x3f, 0x0a, 0x0e, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x54, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x2d, 0x0a, 0x04,
	0x45, 0x63, 0x68, 0x6f, 0x12, 0x11, 0x2e, 0x72, 0x70, 0x63, 0x73, 0x2e, 0x45, 0x63, 0x68, 0x6f,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x72, 0x70, 0x63, 0x73, 0x2e, 0x45,
	0x63, 0x68, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x3a, 0x5a, 0x38, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x6d, 0x61, 0x72, 0x74, 0x63,
	0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x6b, 0x69, 0x74, 0x2f, 0x77, 0x73, 0x72, 0x70, 0x63,
	0x2f, 0x69, 0x6e, 0x74, 0x67, 0x74, 0x65, 0x73, 0x74, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x2f, 0x72, 0x70, 0x63, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_intgtest_internal_rpcs_rpcs_proto_rawDescOnce sync.Once
	file_intgtest_internal_rpcs_rpcs_proto_rawDescData = file_intgtest_internal_rpcs_rpcs_proto_rawDesc
)

func file_intgtest_internal_rpcs_rpcs_proto_rawDescGZIP() []byte {
	file_intgtest_internal_rpcs_rpcs_proto_rawDescOnce.Do(func() {
		file_intgtest_internal_rpcs_rpcs_proto_rawDescData = protoimpl.X.CompressGZIP(file_intgtest_internal_rpcs_rpcs_proto_rawDescData)
	})
	return file_intgtest_internal_rpcs_rpcs_proto_rawDescData
}

var file_intgtest_internal_rpcs_rpcs_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_intgtest_internal_rpcs_rpcs_proto_goTypes = []interface{}{
	(*EchoRequest)(nil),  // 0: rpcs.EchoRequest
	(*EchoResponse)(nil), // 1: rpcs.EchoResponse
}
var file_intgtest_internal_rpcs_rpcs_proto_depIdxs = []int32{
	0, // 0: rpcs.ClientToServer.Echo:input_type -> rpcs.EchoRequest
	1, // 1: rpcs.ClientToServer.Echo:output_type -> rpcs.EchoResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_intgtest_internal_rpcs_rpcs_proto_init() }
func file_intgtest_internal_rpcs_rpcs_proto_init() {
	if File_intgtest_internal_rpcs_rpcs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_intgtest_internal_rpcs_rpcs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EchoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_intgtest_internal_rpcs_rpcs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EchoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_intgtest_internal_rpcs_rpcs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_intgtest_internal_rpcs_rpcs_proto_goTypes,
		DependencyIndexes: file_intgtest_internal_rpcs_rpcs_proto_depIdxs,
		MessageInfos:      file_intgtest_internal_rpcs_rpcs_proto_msgTypes,
	}.Build()
	File_intgtest_internal_rpcs_rpcs_proto = out.File
	file_intgtest_internal_rpcs_rpcs_proto_rawDesc = nil
	file_intgtest_internal_rpcs_rpcs_proto_goTypes = nil
	file_intgtest_internal_rpcs_rpcs_proto_depIdxs = nil
}
